version: '3.4'

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  stripemock:
    image: stripemock/stripe-mock
    ports:
      - "12111:12111"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./run.sh
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - DATABASE_URL=db
      - STRIPE_MOCK_URL=http://stripemock:12111/v1/
    depends_on:
      - db
      - stripemock
    volumes:
      - type: bind
        source: .
        target: /app
