# fly.toml app configuration file generated for glimesh on 2023-05-24T09:10:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "glimesh"
primary_region = "iad"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]

[env]
  ENABLE_LIBCLUSTER = "true"
  HTTP_PORT = "8080"
  PHX_HOST = "glimesh.tv"
  POOL_SIZE = "25"
  PORT = "8080"
  READ_POOL_SIZE = "25"
  URL_HOST = "glimesh.tv"
  URL_PORT = "443"
  URL_SCHEME = "https"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 5000
    soft_limit = 2500

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
