defmodule Glimesh.OldSchema.ChatTypes do
  @moduledoc false
  use Absinthe.Schema.Notation

  import Absinthe.Resolution.Helpers

  alias Glimesh.OldResolvers.ChatResolver
  alias Glimesh.Repo
  alias Glimesh.Streams

  input_object :chat_message_input do
    field :message, :string
  end

  object :chat_mutations do
    @desc "Create a chat message"
    field :create_chat_message, type: :chat_message do
      arg(:channel_id, non_null(:id))
      arg(:message, non_null(:chat_message_input))

      resolve(&ChatResolver.create_chat_message/3)
    end

    @desc "Short timeout (5 minutes) a user from a chat channel."
    field :short_timeout_user, type: :channel_moderation_log do
      arg(:channel_id, non_null(:id))
      arg(:user_id, non_null(:id))

      resolve(&ChatResolver.short_timeout_user/3)
    end

    @desc "Long timeout (15 minutes) a user from a chat channel."
    field :long_timeout_user, type: :channel_moderation_log do
      arg(:channel_id, non_null(:id))
      arg(:user_id, non_null(:id))

      resolve(&ChatResolver.long_timeout_user/3)
    end

    @desc "Ban a user from a chat channel."
    field :ban_user, type: :channel_moderation_log do
      arg(:channel_id, non_null(:id))
      arg(:user_id, non_null(:id))

      resolve(&ChatResolver.ban_user/3)
    end

    @desc "Unban a user from a chat channel."
    field :unban_user, type: :channel_moderation_log do
      arg(:channel_id, non_null(:id))
      arg(:user_id, non_null(:id))

      resolve(&ChatResolver.unban_user/3)
    end

    @desc "Deletes a specific chat message from channel."
    field :delete_message, type: :channel_moderation_log do
      arg(:channel_id, non_null(:id))
      arg(:message_id, non_null(:id))

      resolve(&ChatResolver.delete_chat_message/3)
    end
  end

  object :chat_subscriptions do
    field :chat_message, :chat_message do
      arg(:channel_id, :id)

      config(fn args, _ ->
        case Map.get(args, :channel_id) do
          nil -> {:ok, topic: [Streams.get_subscribe_topic(:chat)]}
          channel_id -> {:ok, topic: [Streams.get_subscribe_topic(:chat, channel_id)]}
        end
      end)
    end
  end

  @desc "Chat Message Token Interface"
  interface :chat_message_token do
    field :type, :string, description: "Token type"
    field :text, :string, description: "Token text"

    resolve_type(fn
      %{type: "text"}, _ -> :text_token
      %{type: "url"}, _ -> :url_token
      %{type: "emote"}, _ -> :emote_token
      _, _ -> nil
    end)
  end

  @desc "Chat Message Text Token"
  object :text_token do
    field :type, :string, description: "Token type"
    field :text, :string, description: "Token text"

    interface(:chat_message_token)
  end

  @desc "Chat Message URL Token"
  object :url_token do
    field :type, :string, description: "Token type"
    field :text, :string, description: "Token text"
    field :url, :string, description: "Token URL"

    interface(:chat_message_token)
  end

  @desc "Chat Message Emote Token"
  object :emote_token do
    field :type, :string, description: "Token type"
    field :text, :string, description: "Token text"

    @desc "Emote Token URL"
    field :url, :string do
      resolve(fn token, _, _ ->
        # This is important for our new emotes system which needs a full qualified URL.
        case token.src do
          "/" <> _ ->
            {:ok, GlimeshWeb.Router.Helpers.static_url(GlimeshWeb.Endpoint, token.src)}

          _ ->
            {:ok, token.src}
        end
      end)
    end

    field :src, :string, description: "Token src URL"

    interface(:chat_message_token)
  end

  @desc "A chat message sent to a channel by a user."
  object :chat_message do
    field :id, :id, description: "Unique chat message identifier"
    field :message, :string, description: "The chat message."

    field :tokens, list_of(:chat_message_token), description: "List of chat message tokens used"

    field :is_followed_message, :boolean,
      description: "Was this message generated by our system for a follow",
      deprecate: "We're going to replace this shortly after launch"

    field :is_subscription_message, :boolean,
      description: "Was this message generated by our system for a subscription",
      deprecate: "We're going to replace this shortly after launch"

    field :channel, non_null(:channel),
      resolve: dataloader(Repo),
      description: "Channel where the chat message occurs"

    field :user, non_null(:user),
      resolve: dataloader(Repo),
      description: "User who sent the chat message"

    field :inserted_at, non_null(:naive_datetime), description: "Chat message creation date"
    field :updated_at, non_null(:naive_datetime), description: "Chat message updated date"
  end

  @desc "A channel timeout or ban"
  object :channel_ban do
    field :channel, non_null(:channel),
      resolve: dataloader(Repo),
      description: "Channel the ban affects"

    field :user, non_null(:user), resolve: dataloader(Repo), description: "User the ban affects"

    field :expires_at, :naive_datetime, description: "When the ban expires"
    field :reason, :string, description: "Reason for channel ban"

    field :inserted_at, non_null(:naive_datetime), description: "Channel ban creation date"
    field :updated_at, non_null(:naive_datetime), description: "Channel ban updated date"
  end

  @desc "A channel moderator"
  object :channel_moderator do
    field :channel, non_null(:channel),
      resolve: dataloader(Repo),
      description: "Channel the moderator can moderate in"

    field :user, non_null(:user), resolve: dataloader(Repo), description: "Moderating User"

    field :can_short_timeout, :boolean, description: "Can perform a short timeout action"
    field :can_long_timeout, :boolean, description: "Can perform a long timeout action"
    field :can_un_timeout, :boolean, description: "Can untimeout a user"
    field :can_ban, :boolean, description: "Can ban a user"
    field :can_unban, :boolean, description: "Can unban a user"
    field :can_delete, :boolean, description: "Can delete a message"

    field :inserted_at, non_null(:naive_datetime), description: "Moderator creation date"
    field :updated_at, non_null(:naive_datetime), description: "Moderator updated date"
  end

  @desc "A moderation event that happened"
  object :channel_moderation_log do
    field :channel, non_null(:channel),
      resolve: dataloader(Repo),
      description: "Channel the event occurred in"

    field :moderator, non_null(:user),
      resolve: dataloader(Repo),
      description: "Moderator that performed the event"

    field :user, non_null(:user),
      resolve: dataloader(Repo),
      description: "Receiving user of the event"

    field :action, :string, description: "Action performed"

    field :inserted_at, non_null(:naive_datetime), description: "Event creation date"
    field :updated_at, non_null(:naive_datetime), description: "Event updated date"
  end
end
