name: Packager

env: 
  MIX_ENV: prod
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ dev ]

jobs:
  package:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14'
          otp-version: '25'

      - name: Install mix dependencies
        run: mix deps.get --only prod, deps.compile

      - name: Install npm assets
        run: npm --prefix ./assets ci --progress=false --no-audit --loglevel=error

      - name: Build glimesh.tv
        run: mix compile

      - name: Build static assets
        run: mix assets.deploy

      - name: Build release
        run: mix release

      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: glimesh-prod-release
          path: _build/prod/rel/glimesh
